version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.34
    - 15.0.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.16
    - 6.2.2
    - 6.2.3
    - 6.2.5
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.4
  - dependency-name: next-pwa
    versions:
    - 5.1.4
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: next
    versions:
    - 10.1.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
  - dependency-name: eslint
    versions:
    - 7.19.0
